language: node_js
before_install: cd the-machine
node_js:
  - "0.11"
  - "0.10"
script: "npm run-script test-travis"
after_script: "npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"