language: node_js
before_install: cd the-machine
env:
  - WEBSITE_TARGET=../website-test
node_js:
  - "8"
script: "npm run test-travis"
after_script: "npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"